<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E7CUST6" failures="1" tests="11" name="testNGpckg.testNGKeyword" time="2.081" errors="1" timestamp="2025-01-02T16:59:52 IST" skipped="2">
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod7" time="0.022"/>
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod9" time="0.004"/>
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod3" time="0.004">
    <system-out>
      <![CDATA[test 3 running]]>
    </system-out>
  </testcase> <!-- testMethod3 -->
  <testcase classname="testNGpckg.testNGKeyword" name="login" time="0.001">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod5" time="2.024">
    <error message="Method testNGpckg.testNGKeyword.testMethod5() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGpckg.testNGKeyword.testMethod5() didn't finish within the time-out 2000
at java.base@17.0.8.1/java.lang.Thread.sleep(Native Method)
at app//testNGpckg.testNGKeyword.testMethod5(testNGKeyword.java:56)
at java.base@17.0.8.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.8.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.8.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.8.1/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.8.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- testMethod5 -->
  <testcase classname="testNGpckg.testNGKeyword" name="register" time="0.007">
    <failure message="fail testcase" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: fail testcase
at org.testng.Assert.fail(Assert.java:111)
at testNGpckg.testNGKeyword.register(testNGKeyword.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- register -->
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod4" time="0.004"/>
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod8" time="0.006"/>
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod6" time="0.008"/>
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod10" time="0.001"/>
  <testcase classname="testNGpckg.testNGKeyword" name="testMethod2">
    <skipped/>
  </testcase> <!-- testMethod2 -->
  <system-out>
    <![CDATA[Before Method Running
Before Method Running
Before Method Running
Before Method Running
test 3 running
Before Method Running
Before Method Running
Before Method Running
Before Method Running
Before Method Running]]>
  </system-out>
</testsuite> <!-- testNGpckg.testNGKeyword -->
