<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E7CUST6" failures="1" tests="1" name="Runner.campaginFunctionality_FailedScenarioRunner" time="0.198" errors="0" timestamp="2024-12-31T10:36:14 IST" skipped="0">
  <testcase classname="Runner.campaginFunctionality_FailedScenarioRunner" name="runScenario" time="0.198">
    <failure message="--------Error in assertion----------- expected [Hello] but found [Hi]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: --------Error in assertion----------- expected [Hello] but found [Hi]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at Steps.campaginFunctionality_FailedScenarioSteps.user_click_on_save_button(campaginFunctionality_FailedScenarioSteps.java:24)
at âœ½.user click on save button(file:///E:/JAVA%20VEL/BDDCucumberProject/src/test/resources/FeatureFile/campaginFunctionality_FailedScenariofeature.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.campaginFunctionality_FailedScenarioRunner -->
